# Generated by Django 4.2.24 on 2025-09-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userr',
            table=None,
        ),
    ]
