# Generated by Django 4.2.24 on 2025-09-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userr_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userr',
            table='user_user',
        ),
    ]
