# Generated by Django 5.2.4 on 2025-07-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userr_created_at_alter_userr_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userr',
            table=None,
        ),
    ]
