# Generated by Django 5.2.4 on 2025-07-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userr_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userr',
            managers=[
            ],
        ),
    ]
