# Generated by Django 5.2.4 on 2025-07-22 17:49

from django.db import migrations

import task_manager.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userr_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userr',
            managers=[
                ('objects', task_manager.user.models.UserrManager()),
            ],
        ),
    ]
