# Generated by Django 5.2.4 on 2025-08-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '__first__'),
        ('tasks', '0003_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(to='labels.labels', verbose_name='label'),
        ),
    ]
