# Generated by Django 5.2.4 on 2025-09-05 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('tasks', '0006_alter_tasks_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='maker',
            new_name='executor',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sts', to='status.statuses'),
        ),
    ]
